# Generated by Django 5.2.5 on 2025-09-10 05:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Adviser', 'Adviser'), ('Panel', 'Panel'), ('Admin', 'Admin')], default='Student', max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'Adviser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_groups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('panel_members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Panel'}, related_name='panel_groups', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'Student'}, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords', null=True)),
                ('status', models.CharField(choices=[('Topic Submission', 'Topic Submission'), ('Topic Review', 'Topic Review'), ('Topic Approved', 'Topic Approved'), ('Topic Rejected', 'Topic Rejected'), ('Proposal Writing', 'Proposal Writing'), ('Proposal Review', 'Proposal Review'), ('Proposal Approved', 'Proposal Approved'), ('Proposal Revision', 'Proposal Revision'), ('Research Phase', 'Research Phase'), ('Writing Phase', 'Writing Phase'), ('Draft Review', 'Draft Review'), ('Final Review', 'Final Review'), ('Defense Ready', 'Defense Ready'), ('Defense Scheduled', 'Defense Scheduled'), ('Defense Completed', 'Defense Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Topic Submission', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'Adviser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_theses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theses', to='api.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ThesisStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('Topic Submission', 'Topic Submission'), ('Topic Review', 'Topic Review'), ('Topic Approved', 'Topic Approved'), ('Topic Rejected', 'Topic Rejected'), ('Proposal Writing', 'Proposal Writing'), ('Proposal Review', 'Proposal Review'), ('Proposal Approved', 'Proposal Approved'), ('Proposal Revision', 'Proposal Revision'), ('Research Phase', 'Research Phase'), ('Writing Phase', 'Writing Phase'), ('Draft Review', 'Draft Review'), ('Final Review', 'Final Review'), ('Defense Ready', 'Defense Ready'), ('Defense Scheduled', 'Defense Scheduled'), ('Defense Completed', 'Defense Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('new_status', models.CharField(choices=[('Topic Submission', 'Topic Submission'), ('Topic Review', 'Topic Review'), ('Topic Approved', 'Topic Approved'), ('Topic Rejected', 'Topic Rejected'), ('Proposal Writing', 'Proposal Writing'), ('Proposal Review', 'Proposal Review'), ('Proposal Approved', 'Proposal Approved'), ('Proposal Revision', 'Proposal Revision'), ('Research Phase', 'Research Phase'), ('Writing Phase', 'Writing Phase'), ('Draft Review', 'Draft Review'), ('Final Review', 'Final Review'), ('Defense Ready', 'Defense Ready'), ('Defense Scheduled', 'Defense Scheduled'), ('Defense Completed', 'Defense Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.thesistopic')),
            ],
            options={
                'verbose_name_plural': 'Thesis Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ThesisDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('proposal', 'Thesis Proposal'), ('chapter1', 'Chapter 1 - Introduction'), ('chapter2', 'Chapter 2 - Literature Review'), ('chapter3', 'Chapter 3 - Methodology'), ('chapter4', 'Chapter 4 - Results'), ('chapter5', 'Chapter 5 - Discussion'), ('final', 'Final Manuscript'), ('defense', 'Defense Presentation')], max_length=50)),
                ('file', models.FileField(upload_to='thesis_documents/')),
                ('original_filename', models.CharField(default='unknown.pdf', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.thesistopic')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('thesis', 'doc_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('thesis_status', 'Thesis Status Update'), ('comment', 'New Comment'), ('evaluation', 'New Evaluation'), ('defense', 'Defense Schedule'), ('assignment', 'New Assignment'), ('reminder', 'Reminder')], max_length=20)),
                ('title', models.CharField(default='Notification', max_length=255)),
                ('message', models.TextField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.thesistopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(default='TBD', max_length=255)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_defenses', to=settings.AUTH_USER_MODEL)),
                ('panel_members', models.ManyToManyField(limit_choices_to={'role': 'Panel'}, related_name='defense_panels', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense_schedule', to='api.thesistopic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', 'General Comment'), ('suggestion', 'Suggestion'), ('correction', 'Correction Required'), ('approval', 'Approval'), ('question', 'Question')], default='general', max_length=20)),
                ('text', models.TextField(default='')),
                ('page_number', models.IntegerField(blank=True, help_text='Page number for document-specific comments', null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('thesis_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.thesisdocument')),
                ('thesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.thesistopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('content', 'Content Quality'), ('methodology', 'Methodology'), ('analysis', 'Analysis & Results'), ('presentation', 'Presentation'), ('originality', 'Originality'), ('overall', 'Overall Assessment')], default='overall', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score out of 100', max_digits=4)),
                ('comments', models.TextField(default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('panel_member', models.ForeignKey(blank=True, limit_choices_to={'role': 'Panel'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.thesistopic')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('thesis', 'panel_member', 'criteria')},
            },
        ),
    ]
