# Generated by Django 5.2.5 on 2025-09-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250910_1335'),
    ]

    operations = [
        # These fields already exist in the initial migration, so we skip them
        # migrations.AddField(
        #     model_name='user',
        #     name='student_id',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='department',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
    ]