# Generated by Django 5.2.5 on 2025-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_drop_legacy_doc_type_id_if_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('thesis_status', 'Thesis Status Update'), ('thesis_submission', 'Thesis Topic Submission'), ('comment', 'New Comment'), ('evaluation', 'New Evaluation'), ('defense', 'Defense Schedule'), ('assignment', 'New Assignment'), ('reminder', 'Reminder')], max_length=20),
        ),
    ]
