# Generated by Django 5.2.7 on 2025-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='thesis_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
