# Generated by Django 5.2.7 on 2025-10-10 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_studentgroup_course_studentgroup_thesis_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('adviser_assigned', 'Awaiting Adviser Confirmation'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('assigned_adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'Adviser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_adviser_proposals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('preferred_adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'Adviser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_adviser_proposals', to=settings.AUTH_USER_MODEL)),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='api.studentgroup')),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'Student'}, related_name='proposed_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
