# Generated by Django 5.2.7 on 2025-10-13 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_update_groupproposal_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('adviser_assigned', 'Awaiting Adviser Confirmation'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupproposal',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='api.studentgroup'),
        ),
    ]
