# Generated by Django 5.2.7 on 2025-10-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_groupproposal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('adviser_assigned', 'Awaiting Adviser Confirmation'), ('adviser_accepted', 'Adviser Accepted - Awaiting Admin Approval'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
